TIMER_SETTINGS = {"Monday": [{'start_hour': 6,
                                'start_min': 0,
                                'end_hour': 23,
                                'end_min': 30,
                                'desired_temp': 24},

                               {'start_hour': 23,
                                'start_min': 31,
                                'end_hour': 23,
                                'end_min': 59,
                                'desired_temp': 20
                                }],
                    "Tuesday": [{'start_hour': 6,
                                 'start_min': 0,
                                 'end_hour': 23,
                                 'end_min': 30,
                                 'desired_temp': 24},

                                {'start_hour': 23,
                                 'start_min': 31,
                                 'end_hour': 23,
                                 'end_min': 59,
                                 'desired_temp': 20
                                 }],
                    "Wednesday": [{'start_hour': 6,
                                   'start_min': 0,
                                   'end_hour': 23,
                                   'end_min': 30,
                                   'desired_temp': 24},

                                  {'start_hour': 23,
                                   'start_min': 31,
                                   'end_hour': 23,
                                   'end_min': 59,
                                   'desired_temp': 20
                                   }],
                    'Thursday': [{'start_hour': 6,
                                  'start_min': 0,
                                  'end_hour': 23,
                                  'end_min': 30,
                                  'desired_temp': 24},

                                 {'start_hour': 23,
                                  'start_min': 31,
                                  'end_hour': 23,
                                  'end_min': 59,
                                  'desired_temp': 20
                                  }],
                    "Friday": [{'start_hour': 6,
                                'start_min': 0,
                                'end_hour': 23,
                                'end_min': 30,
                                'desired_temp': 24},

                               {'start_hour': 23,
                                'start_min': 31,
                                'end_hour': 23,
                                'end_min': 59,
                                'desired_temp': 20
                                }],
                    "Saturday": [{'start_hour': 6,
                                  'start_min': 0,
                                  'end_hour': 23,
                                  'end_min': 30,
                                  'desired_temp': 24},

                                 {'start_hour': 23,
                                  'start_min': 31,
                                  'end_hour': 23,
                                  'end_min': 59,
                                  'desired_temp': 20
                                  }],
                    "Sunday": [{'start_hour': 6,
                                'start_min': 0,
                                'end_hour': 23,
                                'end_min': 30,
                                'desired_temp': 24},

                               {'start_hour': 23,
                                'start_min': 31,
                                'end_hour': 23,
                                'end_min': 59,
                                'desired_temp': 20
                                }]
                    }